In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([-0.35031   , -0.26350023,  1.60821146,  0.66069401,  0.21939909,
        1.08466725, -1.34013592,  1.07674893, -0.42066815, -0.13461322])

In [13]:
B = np.random.randn (10)
B

array([-0.28491389,  0.82360615, -0.18750215, -1.4438511 ,  1.13130515,
        0.03811731, -0.19233748, -0.87802441, -0.48433829,  0.04880895])

In [9]:
# Binary functions
np.add(A,B)

array([-2.68822678,  1.18280143,  0.52046825,  0.01800059, -0.67320986,
        1.32209379, -1.3422348 ,  1.76356297, -2.16045281,  0.08758377])

In [14]:
np.maximum(A,B)

array([-0.28491389,  0.82360615,  1.60821146,  0.66069401,  1.13130515,
        1.08466725, -0.19233748,  1.07674893, -0.42066815,  0.04880895])

In [19]:
website = 'https://www.google.com'
import webbrowser
webbrowser.open(website)

True